# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8d6666820876c19403d082b2b6329e30361aab688bae75b1ed532a9a43bfb2097d84629d66fa5ffd119e65b8ac93814b9daeaea49b000ae0fc551f46c29ed918

test:
  secret_key_base: 6b99a17fe26f5675665a36885de5738f01cecb2b64e512115049d3109c89cb2b1da076171176de1db3778145c72509732db93f69de3a52d5d0dc5b7c3f329c64

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
